### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by dereuromark** [UseMuffin/Slug#13]
I think you should start to release a 1.0 version.
And you can probably remove the .semver noise again in the process.

**Comment by jadb** [comment]
Wil do.

**Comment by josegonzalez** [comment]
Do it.

**Comment by josegonzalez** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0

**Comment by Phillaf** [comment]
HAHAH

**Comment by jadb** [comment]
Done :fireworks:
