### ISSUE TITLE
$length in _uniqueSlug should come from config maxLength

### ISSUE THREAD

**Issue by curtisgibby** [UseMuffin/Slug#21]
Line 292
`$length = $this->config('length');`
should be 
`$length = $this->config('maxLength');`
since `maxLength` is defined in $_defaultConfig and initialize(), while `length` is not.

**Comment by jadb** [comment]
Good catch! Want to submit PR/test?

**Comment by curtisgibby** [comment]
Getting into this, I realized that the `maxLength` configuration option currently only applies to truncation of the potential duplicate (since the `$length` stuff that actually affects anything only happens inside the [`while ($this->_table->exists($conditions))`](https://github.com/UseMuffin/Slug/blob/cd312f6e5b597b1120b35c39b98a6750fb6f7e01/src/Model/Behavior/SlugBehavior.php#L297-L304) loop). Is this the intended behavior?

It seems to me that the `maxLength` config option should be passed into the configured slugger (like in the `_slug` method) to be considered in the generation of the actual pre-suffix slug, not just when considering potential duplicates.

**Comment by jadb** [comment]
> Is this the intended behavior?

No.

**Comment by curtisgibby** [comment]
I decided to do the truncation in the behavior's `_slug` method rather than passing it down to the individual Sluggers.
