### ISSUE TITLE
RFC: optional requirePresence validation rule?

### ISSUE THREAD

**Issue by bravo-kernel** [UseMuffin/Slug#23]
**Situation:**

- I have `UsersTable` with `username` field and SlugBehavior attached to this field
- I recently decided to no longer require `username` field during user registration flow
- thus removed related validation rules from my `UsersTable`.

**However:**

Creating a new user record without POSTing `username` field now throws a `required` field validation error, caused by [this SlugBehavior validation rule](https://github.com/UseMuffin/Slug/blob/master/src/Model/Behavior/SlugBehavior.php#L173).

**Question:**

Is there already a way to make the SlugBehavior validation rule optional and if not... would a PR be welcome? Suggestions welcome.

**Comment by jadb** [comment]
This is already possible.

Just disable the `Model.buildValidator` event on the behavior by passing this option:

```php
'implementedEvents' => [
    'Model.beforeSave' => 'beforeSave'
]
```

**Comment by bravo-kernel** [comment]
Thank you very much mr. @jadb, did not realize that.
