### ISSUE TITLE
How to create slug if web application is multilingual ?

### ISSUE THREAD

**Issue by nk-nareshkumar** [UseMuffin/Slug#33]
Hi,

My question is how to create slug if web application is multilingual ?
if i have two name fields name_en and name_spa then how to work with this plugin to generate slug for English and Spanish like slug_en, slug_spa 
and after this how to use search option to get result from slug_en and slug_spa  

Thanks,
Naresh Kumar

**Comment by davidyell** [comment]
This plugin doesn't support multiple slugs in the same table class.

You'll have to create the second slug manually yourself. This is how I've done it in my Table class.

```php
    /**
     * Generate a slug for the display field
     *
     * @param Event $event
     * @param EntityInterface $entity
     * @return bool
     */
    public function beforeSave(Event $event, EntityInterface $entity)
    {
        if (!empty($entity->get('display_name'))) {
            /* @var \Muffin\Slug\Model\Behavior\SlugBehavior $slugBehaviour */
            $slugBehaviour = clone $this->behaviors()->get('Slug');
            $slugBehaviour->setConfig([
                'field' => 'display_name_slug',
                'displayField' => 'display_name',
                'onUpdate' => true
            ]);

            $slugBehaviour->beforeSave($event, $entity, new \ArrayObject());
        }

        return true;
    }
```

**Comment by ADmad** [comment]
Closing as the question has been answered.
